# Alembic configuration file
# This file is used by the Alembic migration tool.
# https://alembic.sqlalchemy.org/

[alembic]
# Path to migration scripts
script_location = %(here)s/database/migrations
version_locations = %(here)s/database/migrations/versions

# Template used to generate migration file names
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path to add for env.py
prepend_sys_path = .

# Timezone to use when rendering the date within the migration file
# timezone =

# Max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# Set to 'true' to run the environment during alembic revision
# revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without a source .py file
# sourceless = false

# Version path separator
# version_path_separator = os  # Use os.pathsep

# The output encoding used when revision files are written
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://techhunt:techhunt_dev@localhost:5432/techhunt


[post_write_hooks]
# No post-write hooks configured

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
